# Generated by Django 5.1.1 on 2024-11-23 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pedidos',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='administrador.pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_relacionados', to='administrador.venta'),
        ),
    ]
