# Generated by Django 5.1.1 on 2024-11-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_venta_pedidos_alter_pedido_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='pedidos',
        ),
    ]
