# Generated by Django 5.1.1 on 2024-11-23 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_pedido_venta_venta_pedidos_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='pedidos_venta',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_venta', to='administrador.venta'),
        ),
    ]
