# Generated by Django 5.1.1 on 2024-11-23 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_remove_venta_pedidos_venta_alter_pedido_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='importeTotal',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
