# Generated by Django 5.1.1 on 2024-11-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0013_producto_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='venta',
        ),
    ]
