# Generated by Django 5.1.1 on 2024-12-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0015_pedido_user_venta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cuotas',
            field=models.IntegerField(default=5),
        ),
    ]
